from data_collection.indeed_scraper import scrape_indeed_jobs
from data_collection.glassdoor_scraper import scrape_glassdoor_jobs
from data_collection.linkedin_scraper import scrape_linkedin_jobs

scrape_indeed_jobs()
scrape_glassdoor_jobs()
scrape_linkedin_jobs()